### ISSUE TITLE
Adding sub categories

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/petitesannonces_ynh#9]
Hello, this small cms is really great
I would like to enhance by adding sub- categories, is it possible ?
Sincerely.
Yvan

**Comment by anto1ne** [comment]
Hi @tutle 

Thank you for using petitesannonces :smile: 

This area should be used to report issues about petitesannonces_ynh (the yunohost apps for petitesannonces)

Issues about petitesannonces should be reported [here](https://framagit.org/anto1ne/petitesannonces) 

Your feature request has been reported [here](https://framagit.org/anto1ne/petitesannonces/-/issues/16)

To answer you shortly, it is not yet possible to add sub categories.

The easiest way today would be to create categories named with a pattern like "Category - sub-category"


--------
Bonjour,

Ce n'est pas le bon endroit pour rapporter un bug sur petitesannonces, ici c'est pour l'installateur yunohost de petitesannonces.
Ce n'est pas grave, j'ai fait le transfert.

Il n'est pas possible d'avoir des sous-catégories aujourd'hui.
Le moyen le plus simple aujourd'hui pour combler ce besoin est de créer des catégories avec des noms faisant apparaître des sous-catégories  du style "Catégorie - sous-categorie". (il faut par contre mettre un peu les mains dans la base de données pour ajouter/modifier les catégories, ce n'est pas simple si on ne connaît pas)

J'espère que ma réponse est claire. 

Je ne travaille plus sur cette app depuis un petit moment, toute contribution est la bienvenu
https://framagit.org/anto1ne/petitesannonces

Et merci pour ton intérêt pour cette application et ce rapport de bug.
